# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iawJ6u-o9jinwaMSvrerP9NXdwLADhQH
"""

from gtts import gTTS
from IPython.display import Audio

# Text to convert
text = "Hello, welcome Afra in AI/ML engineering feild"

# Create speech
tts = gTTS(text=text, lang='en')  # You can use 'ur' for Urdu, 'hi' for Hindi, etc.
tts.save("output.mp3")  # Save file

# Play the audio
Audio("output.mp3")